USE [master]
GO

/****** Object:  Database [BilleteraVirtual]    Script Date: 23/11/2022 21:21:40 ******/
CREATE DATABASE [BilleteraVirtual]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BilleteraVirtual', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BilleteraVirtual.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BilleteraVirtual_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BilleteraVirtual_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BilleteraVirtual].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BilleteraVirtual] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET ARITHABORT OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BilleteraVirtual] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BilleteraVirtual] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BilleteraVirtual] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BilleteraVirtual] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BilleteraVirtual] SET  MULTI_USER 
GO

ALTER DATABASE [BilleteraVirtual] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BilleteraVirtual] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BilleteraVirtual] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BilleteraVirtual] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BilleteraVirtual] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BilleteraVirtual] SET  READ_WRITE 
GO

