USE [master]
GO

/****** Object:  Database [MiBilleteraVirtual]    Script Date: 08/12/2022 10:59:38 ******/
CREATE DATABASE [MiBilleteraVirtual]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiBilleteraVirtual', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MiBilleteraVirtual.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MiBilleteraVirtual_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MiBilleteraVirtual_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiBilleteraVirtual].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MiBilleteraVirtual] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET ARITHABORT OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MiBilleteraVirtual] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MiBilleteraVirtual] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MiBilleteraVirtual] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MiBilleteraVirtual] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MiBilleteraVirtual] SET  MULTI_USER 
GO

ALTER DATABASE [MiBilleteraVirtual] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MiBilleteraVirtual] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MiBilleteraVirtual] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MiBilleteraVirtual] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MiBilleteraVirtual] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MiBilleteraVirtual] SET  READ_WRITE 
GO

